"""birds.avg_eggs optional

Revision ID: 2aa013cd8cdf
Revises: 500ef6d657e1
Create Date: 2025-01-19 23:03:09.533774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa013cd8cdf'
down_revision: Union[str, None] = '500ef6d657e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('birds', 'avg_eggs_per_month',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('birds', 'avg_eggs_per_month',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
