"""birds.coop_oid fix

Revision ID: 500ef6d657e1
Revises: 0fcac8534431
Create Date: 2025-01-19 22:58:38.657075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500ef6d657e1'
down_revision: Union[str, None] = '0fcac8534431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds', sa.Column('coop_oid', sa.UUID(), nullable=False))
    op.drop_column('birds', 'coop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds', sa.Column('coop_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('birds', 'coop_oid')
    # ### end Alembic commands ###
