"""coop_oid fk

Revision ID: 542f2ad99ebf
Revises: 2aa013cd8cdf
Create Date: 2025-01-20 14:21:43.531114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542f2ad99ebf'
down_revision: Union[str, None] = '2aa013cd8cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('birds_coop_oid_fkey', 'birds', 'coops', ['coop_oid'], ['oid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('birds_coop_oid_fkey', 'birds', type_='foreignkey')
    # ### end Alembic commands ###
