"""birds and coops

Revision ID: f3a356122c16
Revises: 
Create Date: 2024-09-22 19:16:46.075560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a356122c16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('coop_id', sa.UUID(), nullable=False),
    sa.Column('avg_eggs_per_month', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_birds_name'), 'birds', ['name'], unique=False)
    op.create_table('coops',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coops')
    op.drop_index(op.f('ix_birds_name'), table_name='birds')
    op.drop_table('birds')
    # ### end Alembic commands ###
